version: '3.8'

services:
  db:
    image: postgres:10
    container_name: postgres_container
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatapp
    ports:
      - "5555:5432"  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
